version: "3" 
services:
  frontend:
    build: frontend
    #host/container
    ports:
      - 80:80
    #Definir variable de entorno
    environment:
      - NODE_OPTIONS=--max-old-space-size=4096    
    
    
  backend:
    build: backend
    ports:
      - 8080:8080
    depends_on:
      - db

  #database     
  db:
    build: db/mysql-init/init.sql
    ports:
    - 3306:3306
    volumes:
    - ./db/mysql-init/init.sql

volumes:
  mysql-data: