version: '3.8'
services:
  frontend:
    build: frontend
    ports:
      - 80:80
    environment:
      - NODE_OPTIONS=--max-old-space-size=4096

  backend:
    build: backend
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: mysql:5.7
    command: --explicit_defaults_for_timestamp=ON
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: restaurant_reservations
      MYSQL_USER: restaurant
      MYSQL_PASSWORD: restaurant
    ports:
      - "3306:3306"
    volumes:
      - ./db/mysql-init:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: