version: "3" 
services:
  frontend:
    build: frontend
    #host/container
    ports:
      - 80:80
    #Definir variable de entorno
    environment:
      - NODE_OPTIONS=--max-old-space-size=4096    
    depends_on:
      - backend
    
    
  backend:
    build: backend
    ports:
      - 8080:8080
    depends_on:
      - db

  #database     
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:${MYSQL_PORT}"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql-data:
